Tightened up linting and fixed all linter issues (#13)
Signed-off-by: Ed Warnicke <hagbard@gmail.com>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,33 +1,24 @@
 ---
 version: 2.1
 
+orbs:
+  shellcheck: circleci/shellcheck@1.3.15
+
 jobs:
 
-# sanity
-  checks:
-    working_directory: /go/src/github.com/networkservicemesh/cloudtest
+  # sanity
+  go-checks:
     docker:
       - image: circleci/golang:1.13-stretch
     steps:
       - checkout
       - run:
-          name: Install Shellcheck
-          command: ./.circleci/install-shellcheck.sh
-      - run:
-          name: Run Shellcheck
-          command: shellcheck `find . -name "*.sh" -not -path "*vendor/*"`;
-      - run:
-          name: Run Error Usage Check
-          command: ./.circleci/check_errors.sh
-      - run:
-          name: Check code formatting
+          name: Run fmt.Errorf Usage Check
           command: |
-            GO111MODULE=off go get -u golang.org/x/tools/cmd/goimports
-            GO111MODULE=on goimports -w -local github.com/networkservicemesh/sdk -d .
-            git diff --exit-code || (echo 'Seems like your Go files are not properly formatted. Run goimports -w -local github.com/networkservicemesh/sdk -d . in your branch and commit the changes.' && exit 1)
-      - run:
-          name: Go Vet
-          command: go vet --all ./...
+            if grep -r --include=*.go fmt.Errorf . ; then
+              echo "Please use errors.Errorf (or errors.New or errors.Wrap or errors.Wrapf) as appropriate rather than fmt.Errorf"
+              exit 1
+            fi
       - run:
           name: Build
           command: go build ./...
@@ -53,12 +44,22 @@ jobs:
           path: ~/junit
     environment:
       GO111MODULE: "on"
-
-
+  yaml-checks:
+    docker:
+      - image: circleci/python:3.7.2
+    steps:
+      - checkout
+      - run:
+          name: yamllint
+          command: |
+            pip install --user yamllint
+            /home/circleci/.local/bin/yamllint -c .yamllint.yml --strict .
 
 # workflows
 workflows:
   version: 2
   checks:
     jobs:
-      - checks
+      - go-checks
+      - yaml-checks
+      - shellcheck/check
